services:
  - type: web
    name: rbhairoasis
    env: docker
    plan: free
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile        # Dockerfile exposes port 8000
    healthCheckPath: /                 # optional: "/" returns 200
    envVars:
      - key: APP_NAME            # ↓ consider moving secrets into Render UI
        value: RBHairOasis
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:KMEMzZVhkVlBnuaPdEQoG0EknVHiphYFmJNGT79yEZ0=
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://rbhairoasis.onrender.com

      # --- Database ---
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: dpg-d0h6r93e5dus73bcvq9g-a
      - key: DB_PORT
        value: "3306"        # MySQL default
      - key: DB_DATABASE
        value: rbhairoasis
      - key: DB_USERNAME
        value: rbhairoasis_db_user
      - key: DB_PASSWORD
        value: pHDe8CEimKuKCqnktAFhDv5I7PH9E6hq

      # Filesystem
      - key: FILESYSTEM_DRIVER
        value: public
